### ISSUE TITLE
Cursor blinking speed

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#128]
OK, this one will look like I have nothing better to do then to open useless issues ;) but I've been wondering whether it isn't something easy to fix -- right now, if you look at a text field with cursor inside you'll notice that it has a periodic "heart beat" which is however broken every time the refresh cycle kicks in (you can literally see it "reset" to the - \ | / - changes).

This happens despite the fact that nothing is changed on the screen, just the cursor is blinking.

**Comment by atarijookie** [comment]
This is due to the added hearth beat char in the config stream, it needs redrawing each second, and that makes the cursor blink. If you don't like the blinking (and I guess it causes linux ce_conf to flash the whole screen), then I can remove it - I thought it would be a good idea to let the user know that the thing is alive, but if the blinking / flickering is such annoyance, I will remove it.

**Comment by mikrosk** [comment]
I agree, the alive char is sweet. Isnt possible to sync blinking to that? Or its standard tos functionality and you can't control it?

**Comment by atarijookie** [comment]
Well, I don't know how to detect when the cursor blinks off and on, so I can't sync to that... There could be a guess (measurement) to do it at the same time as TOS does, but it still might be out of sync...
