### ISSUE TITLE
Shouldn't CE disable mouse in joystick mode?

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#130]
During my investigation in #129 I've found out an interesting bug/feature -- if the user instructs the IKBD to be in Joystick event reporting mode, both (ikbd) joysticks do what they are supposed to do, i.e. reporting fire/direction changes.

However, if usb mouse is connected, we feed the ST with mouse packets. This is of course cool in the desktop because it allows the cursor to move no matter what mode is set but on the other hand, I've seen it crash a game simply because it wasn't prepared to receive a mouse packet (and it's a valid assumption, no mouse packet should make it trough until a mouse command is issued; please note this is different than reporting bogus "joystick" packets when mouse is connected and moved in a joystick mode!).

Same goes for the usb joystick0, we shouldn't mix mouse and joystick packets, IMHO. What do you think?

**Comment by atarijookie** [comment]
> What do you think?

I think that the IKBD tests would map the original behavior and show exactly what everything is wrong with CE IKDB emulation :) It sounds silly to write this in every IKBD issue you open, but that is the way to go - instead of guessing what is right, what is wrong and what CE does, this would tell us exactly... This way you will open another 30 IKBD issues, which we might not be able to directly respond to, as we don't know exactly what the original IKBD really does. Sooo, once again -  could you, please, help me with IKBD tests? :)

**Comment by mikrosk** [comment]
Eh, how exactly would you plan to write a test for having joy0 and mouse connected in the same time? This is 100% CE related issue.

**Comment by miniupnp** [comment]
I think indeed the mouse packets should not be injected if a joystick is supposed to be connected to port 0
Or maybe this can be a config option "do not send mouse packets when IKBD port 0 is in joystick mode"

**Comment by mikrosk** [comment]
Trouble is you can't really know this in advance -- in desktop is super beneficial (both joysticks connected and still have a [usb] mouse) . In a game, on the other hand, it can have disastrous implications. 

Hmm... now reading after myself:

> if the user instructs the IKBD to be in Joystick event reporting mode, both (ikbd) joysticks do what they are supposed to do, i.e. reporting fire/direction changes.

The desktop doesn't do this by default, i.e. the IKBD is set to mouse mode for joy0. So perhaps you're right Thomas, we should disable it.

**Comment by atarijookie** [comment]
Closing, when someone will work on this later, he can reopen it :)
