### ISSUE TITLE
use inotify instead of polling

### ISSUE THREAD

**Issue by miniupnp** [atarijookie/ce-atari#135]
in the main app, I noticed there are threads which are polling directories (ikbd polls /dev/input/by-path) 
I would be more memory/cpu efficient to use inotify
I think the dev finder polls /dev/disk/by-id as well

**Comment by mikrosk** [comment]
This is a nice idea. Perhaps some other stuff could be moved away from the periodic thread, too (input keyboard/joystick events?).

**Comment by miniupnp** [comment]
keyboard/joystick events are polled ? arghhhh

**Comment by mikrosk** [comment]
I think it's because of simplicity/consistency -- CE asks whether there are some IKBD commands pending and while there, it asks for Linux keys/joysticks as well.

But if it's possible to have an event (interrupt) driven IKBD handling (i.e. if there's a "RECV buffer not empty" interrupt for the RPi's pins) then it would make sense to get rid of the polling, sure.

**Comment by miniupnp** [comment]
well Ikbd::processReceivedCommands(void) has the code
`int res = read(fdUart, pBfr, 127);`
so you should be able to select() fdUart, aren't you ?

**Comment by mikrosk** [comment]
Damn, you're right. It has been long time ago since I played with select's and stuff. Yeah, it sounds like a plan to me. ;)

**Comment by miniupnp** [comment]
```
fdset rfds;
int max_fd;
FD_ZERO(&rfds);
max_fd = 0;
foreach fd {
 if(fd >= 0) {
  FD_SET(fd, &rdfs);
  if(fd > max_fd) max_fd = fd;
}
select(max_fd, &rfds, NULL, NULL, &timeout);
foreach(fd) {
  if(fd >= 0 && FD_ISSET(fd, &rfds)) {
    process();
  }
}
```

**Comment by miniupnp** [comment]
I nearly had an heart attack ;)

**Comment by miniupnp** [comment]
and of course the inotify socket can be added to the select() set
