### ISSUE TITLE
Download disk from the Internet bombs out

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#157]
OK, so #156 wont let me copy anything so I thought I'd download something. Press F9, mark, download, file selector, progressing... by 100% it says communication error and bombs out.

However, I can open the downloaded ZIP -> MSA -> mount and reset.

**Comment by miniupnp** [comment]
what's the logs on the CE ?

**Comment by atarijookie** [comment]
Probably related to trying to mount ZIPed image + the enabled ZIP DIRs support + some weird / unhandled response in CE_FDD... This might get solved / worked around by doing #182

**Comment by atarijookie** [comment]
I'm not able to crash the app the way you described, but I managed to crash it in a different way, for which I don't have the explanation yet:
when you are in the download images screen. hold down the DOWN arrow to keep scrolling through images and pages on end of each page, and in few pages I get bomb when loading / showing the page... The data and logs on CE look normal... 
This looks like it takes longer time to redraw the screen (because redrawing all search results), and when holding down the keyboard button, the IKBD buffer overflows during that time or something...

**Comment by atarijookie** [comment]
Okay, now I'm able to get it in weird states, but I must not touch anything else (no mouse interaction, no other keys):
start CE_FDD.PRG
F9 (switch to download page)
F1 (mark)
F3 (download)
...file selector pops up, I press ENTER
...download starts, app freezes :-o

```
handleAcsiCommand: 00 43 45 05 2d 00
handleAcsiCommand - CE specific command - module: 05
floppySetup command: FDD_CMD_SEARCH_DOWNLOAD
CConSpi - didn't TX/RX enough data, padding with 10 zeros! Fix this!
```

It looks like the method void FloppySetup::searchDownload(void) in ce_main_app goes some path which ends up in not returning data to ST (e.g. not setting statusStr, or skipping setting it using dataTrans->addDataBfr(), which ends up in ST being confused... Weird...

**Comment by atarijookie** [comment]
That state machine in **FloppySetup::searchDownload(void)** is totally weird... I don't know what kind of drugs I was abusing when I wrote that ;) but I should never do them again :-D

Anyway, after working on #181 (floppy images download and insert through browser) and looking at the mess in FloppySetup::searchDownload(void) I realized / decided, that this should be done in a different way - just like in #181. More details about it are in #183. After that will be done, this issue will be tested once again, but as that code went through major changes, this issue shouldn't appear after that...

**Comment by atarijookie** [comment]
Floppy image download now being in the remake process, so this exact issue won't happen, so closing it.
