### ISSUE TITLE
Xilinx update fails on the dev image when done from UI

### ISSUE THREAD

**Issue by mikrosk** [atarijookie/ce-atari#78]
What I basically did:

1. Autostarted /ce/ce_start.sh as described in #73 
1. Started up ce_conf.prg
1. Saw the main app and xilinx available
1. Main app went fine but xilinx just hanged...

Repeated attempts also didn't help (even when trying the UI on Linux), I had to manually run /ce/ce_update.sh twice to make it working.

**Comment by atarijookie** [comment]
Xilinx takes ~50 - ~60 seconds, are you sure you didn't just have to wait long enough? :) 

You can't show the real progress of these because they are needed for communication with ST, but there could be an enhancement - the linux app could tell the CE_CONFIG what it will update, and CE_CONFIG then could show some fake progress...

**Comment by mikrosk** [comment]
I'm not _totally_ sure but I'm _fairly_ sure I'd waited long enough. Right now I can't try again (as I'm on Raspbian already and don't have any other SD card) but it was really as straightforward as that so perhaps you can try it out.

**Comment by atarijookie** [comment]
As we don't know what happened, and as the new CE_CONF.PRG will report the progress nicely (in the next update, not in this one), then don't know what to do with this one, so closing :)
